name: Library Builder CI

on:
  repository_dispatch:
  workflow_dispatch: 

defaults:
  run:
    working-directory: dargon2

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make library
      run: |
        git clone https://github.com/P-H-C/phc-winner-argon2.git argon2_library
        cd argon2_library
        make
    - name: Copy Compiled Library
      run: |
        mkdir -p lib/src/blobs/
        cp argon2_library/libargon2.so.1 lib/src/blobs/libargon2-linux.so
    - name: Check if there are changes
      run: |
        function check() {
          if [[ -z "$(git status --porcelain)" ]];
          then
            echo "0"
          else
            echo "1"
          fi
        }
        echo "CHANGED=$(check)" >> $GITHUB_ENV
    - name: Push if Changed
      if: ${{ env.CHANGED == '1' }}
      run: |
        git config user.name  "Github Actions"
        git config user.email "GH-actions-ci@github.com"
        git add -f lib/src/blobs/libargon2-linux.so
        git commit -m "Create Native Library for Linux"
        git push origin ${GITHUB_REF##*/}
  mac-build:
    runs-on: macos-latest
    needs: linux-build
    steps:
    - uses: actions/checkout@v2
    - name: Get Updated Changes
      run:  git pull origin ${GITHUB_REF##*/}
    - name: Make & Copy Library
      run: |
        git clone https://github.com/P-H-C/phc-winner-argon2.git argon2_library
        cd argon2_library
        make
        mv libargon2.1.dylib libargon2.1-x86_64.dylib
        make clean
        CFLAGS=--target=arm64-apple-macos11 make OPTTARGET=aarch64
        mv libargon2.1.dylib libargon2.1-arm64.dylib
        lipo -create libargon2.1-x86_64.dylib libargon2.1-arm64.dylib -output libargon2.1.dylib
        cd ..
        cp argon2_library/libargon2.1.dylib lib/src/blobs/libargon2-darwin.dylib
    - name: Check if there are changes
      run: |
        function check() {
          if [[ -z "$(git status --porcelain)" ]];
          then
            echo "0"
          else
            echo "1"
          fi
        }
        echo "CHANGED=$(check)" >> $GITHUB_ENV
    - name: Push if Changed
      if: ${{ env.CHANGED == '1' }}
      run: |
        git config user.name  "Github Actions"
        git config user.email "GH-actions-ci@github.com"
        git add -f lib/src/blobs/libargon2-darwin.dylib
        git commit -m "Create Native Library for Mac"
        git push origin ${GITHUB_REF##*/}
  